name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          components: clippy,rustfmt
          override: true

    - name: Formatting
      run: cargo fmt --check --verbose

    - name: Clippy (server)
      uses: giraffate/clippy-action@v1
      with:
        clippy_flags: --features ssr

    - name: Clippy (client)
      uses: giraffate/clippy-action@v1
      with:
        clippy_flags: --features hydrate
